var quotes = [
"Waiting for other players to make their move...", 
"Tap PLAY to bust a move!", 
"Have you ever noticed how the King of Diamonds stares at the Queen of Hearts?", 
"Do you ever wonder what people do when they are waiting for your move?", 
"Knock, knock...", 
"My name is McLaugh. Jack McLaugh...", 
"Why six was scared of seven? Because seven 'ate' nine.", 
"How do you count cows? With a cowculator.", 
"How astronomers organise their parties? They planet.", 
"Why do leopards hate hide and seek? Because they are always spotted.", 
"What do you call a bear with no teeth? A gummy bear.", 
"Did you ever notice that your nose runs but your feet smell?", 
"Why do shrimps never donate to charity? They are shellfish.", 
"Why are cows so noisy? Because they have horns."
]
//creating an array to store inside the used quotes
var usedQuotes=[];
//here I create a function to generate random numbers
var genRandomNumber = function(){ 
	return Math.floor(Math.random() * (quotes.length));
}

var randomNumber = null;


//creating a for loop to go through the used quotes array and check if the given quote exists in the array copy.
//if it does we should fetch another one
//if it doesn't or returns null we should store it on the array copy and trigger the quote
//This function triggers that we want a new quote

function newQuote() {

	//console.log("STARTED newQuote function");

	//first I wanna check if the usedQuotes array has become equal or bigger than the quotes
	//since this means that we've stored already all possible quotes in usedQuotes and have to restart
	if (usedQuotes.length >= quotes.length){
		usedQuotes.length = 0;
 	}
//Here I check if the usedQuotes array has something in it to check if we've used a quote already

 	 if( usedQuotes.length > 0){
		randomNumber = genRandomNumber();
			//here I go through the usedQuotes array to check if the quote has already been stored in the used array
		for (var i = 0; i <= usedQuotes.length; i++){
			console.log("testing the forloop: "+i);
		
			// we go through the usedQuotes array and check if it matches the quotes[random] generated by the shuffler
			if (usedQuotes[i] != quotes[randomNumber]) {
				//here i'm feeding the new quote to the html doc
				document.getElementById('quoteDisplay').innerHTML = quotes[randomNumber];
			}
		}
		//here i'm pushing the quote[random] inside the usedQuotes array since it was not repeated
				usedQuotes.push(quotes[randomNumber]);
		/* 	else {
				//here i'm pushing the quote[random] inside the usedQuotes array since it was not repeated
				usedQuotes.push(quotes[randomNumber]);
				//here i'm feeding the new quote to the html doc
				document.getElementById('quoteDisplay').innerHTML = quotes[randomNumber];

				console.log("Checking if usedQuotes: " + usedQuotes[i] + " is equal to: " + quotes[randomNumber]);
			}

		}
	} */

 	}

		//Here i wanna check if usedQuotes array is empty. This means the function hasn't been used yet or has been restarted
	else  {
	
 		randomNumber = genRandomNumber();
		//first thing we display the first quote on the html 
		document.getElementById('quoteDisplay').innerHTML = quotes[randomNumber];
		//then we push this first quote into the usedQuotes array
		usedQuotes.push(quotes[randomNumber]);

		console.log("Random num generated: "+ randomNumber+ " usedQuotes lengh t= "+ usedQuotes.length);
	}
	


}