var quotes = [
"Waiting for other players to make their move...", 
"Tap PLAY to bust a move!", 
"Have you ever noticed how the King of Diamonds stares at the Queen of Hearts?", 
"Do you ever wonder what people do when they are waiting for your move?", 
"Knock, knock...", 
"My name is McLaugh. Jack McLaugh...", 
"Why six was scared of seven? Because seven 'ate' nine.", 
"How do you count cows? With a cowculator.", 
"How astronomers organise their parties? They planet.", 
"Why do leopards hate hide and seek? Because they are always spotted.", 
"What do you call a bear with no teeth? A gummy bear.", 
"Did you ever notice that your nose runs but your feet smell?", 
"Why do shrimps never donate to charity? They are shellfish.", 
"Why are cows so noisy? Because they have horns."
]
//creating an array to store inside the used quotes
var usedQuotes=[];
//creating a for loop to go through the used quotes array and check if the given quote exists in the array copy.
//if it does we should fetch another one
//if it doesn't or returns null we should store it on the array copy and trigger the quote


//This function triggers that we want a new quote
function newQuote() {
	//here I create a function to generate random numbers
	var genRandomNumber = function(){ 
		return Math.floor(Math.random() * (quotes.length));
	}
	//here we are just generating a random number with the lenght of the array to randomly pick a quote from the main array
var randomNumber = genRandomNumber();
console.log("Rnadom num generated: "+ randomNumber);

	//here i should check if the given quote is already on the usedQuotes array
	for (var i=0; i <= usedQuotes.length; i++){
		console.log("for loop started");
	//here i'm first checking if the usedQuotes array is already 'filled' meaning that we've gone through all the quotes array
	//already one full time. If this is the case I reset the usedQuotes array back to null
	if (usedQuotes.length == quotes.length){
		usedQuotes=[];
	}
	
	//if the usedQuotes array is not yet equal to the quotes array in lenght it means that there are unused strings there
	//So we go through the usedQuotes array and check if it matches the quotes[random] generated by the shuffler
	else {
		console.log("started the else condition");

		if (usedQuotes[i] != quotes[randomNumber] || null) {
			console.log("successfully checked if there is a match of strings");
			//here i'm pushing the quote[random] inside the usedQuotes array since it was not repeated
			usedQuotes.push(quotes[randomNumber]);
			//here i'm feeding the new quote to the html doc
			document.getElementById('quoteDisplay').innerHTML = quotes[randomNumber];
		}
		genRandomNumber();
	
	console.log("Lenght of usedQuotes array: "+ usedQuotes.length);
	}

}


}